name: Go Test

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: [1.21,"1.20"]

    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sed -i 's/1.21/${{matrix.go}}/g' go.mod
        go mod download
        go mod tidy
        
    - name: Run tests
      run: go test -v ./...